# Generated by Django 5.1.7 on 2025-03-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен')], default='pending', max_length=20),
        ),
    ]
